### ISSUE TITLE
1.7.1 is not compatible with Ruby 1.8.7 anymore

### ISSUE THREAD

**Issue by jlecour** [jugyo/g#4]
Hi,

In the 2c37fb1575 commit (in the `1.7.1` release) using `require_relative` instead of `require` broke the compatibility with Ruby 1.8.7

I don't have any particular grief with going >= 1.9 only, but doing this without a warning in the README and in a patch release is not great.

Following [SemVer](http://semver.org) recommendations, you should revert this commit in a 1.7.2 release and make a 2.0 release.

Anyway, thanks for maintaining `g`. I really like it.

**Comment by jugyo** [comment]
I'm sorry to break compatible with 1.8.7. The problem has been solved and new version 1.7.2 has been released. Please check it out.

Thank you :smile:
